### ISSUE TITLE
Magyar Kupa megyei csapatok

### ISSUE THREAD

**Issue by GuberPeter** [bertadenes/tippelde#14]
Melyik megye megyei szintű csapata jut legtovább a Magyar Kupában? 2 megyét jelölhetnek, legördülő listából lenne legcélszerűbb.

Pontozás: 15/találat - több helyes válasz is lehet, mert lehet, hogy azonos körben esnek ki többen!

**Comment by bertadenes** [comment]
duplicate of #29
