### ISSUE TITLE
Egy üres lap - Tippelde Kupa

### ISSUE THREAD

**Issue by GuberPeter** [bertadenes/tippelde#24]
A Tippelde Kupa lebonyolításába teljesen felesleges belemennem, annyira bonyolult, számolom ezt kézzel (szorosan nem tartozik a bajnokság pontozásához, tényleg mindegy is).

Csak annyit kérek, hogy nyiss kérlek egy "Tippelde Kupa" fület, ahová sima text alapon vagy valami szövegszerkesztő toollal tudok írogatni.

**Comment by bertadenes** [comment]
Ha jol ertem azt szeretned hogy te tudj irni valamit majd azt a tobbiek lassak, es ezt tudd modositani?

**Comment by GuberPeter** [comment]
Pontosan. De ehhez semmiféle pontozás vagy ilyesmi nem kell, hogy társuljon, egyszerűen egy felület, ahová tudok írni. Amúgy felőlem akár lehet a főoldalon is. Ahonnan amúgy szerintem kitörölheted a hosszú szöveget, mert issue-ként létrehoztam közülük mindent, illetve a kiírásba is belefoglaltam (amit átdobtam html-ben, ha sikerült)

**Comment by bertadenes** [comment]
Most mar adhatsz hozza amit csak akarsz
