### ISSUE TITLE
Módosítások leadásának határideje - low priority

### ISSUE THREAD

**Issue by GuberPeter** [bertadenes/tippelde#26]
Azt meg tudnám esetleg adni, hogy meddig tudják módosítani a tippeket?
Illetve hol jelennek meg a honlapon azok a dolgok, amiket tudnak módosítani? Hol látják, hogy hány lehetőségük van még erre?

Nem sürgős, mert legkorábban a 11. fordulóban lehet módosítani (kivéve gólkirályt), a többséget meg csak télen.

**Comment by bertadenes** [comment]
Gyakorlatilag a meccseket akarhanyszor lehet modositani a kezdesig, a kerdeseket pedig megadott szamu alkalommal a 'due'-ban megjelolt idopontig. A kerdes reszletes oldalan elvileg kiirja hanyszor lehet valtoztatni.
Van valami mas amire szukseg van ezzel kapcsolatban?

**Comment by GuberPeter** [comment]
A meccsek rendben vannak, a kérdésekre vonatkozik ez inkább. Belegondolva, igazából ez nem teljesen jó, de paraszti logikával azért simán használható.

Itt ugye a tökéletes megoldás az lenne, hogy a kérdés létrehozásakor meg tudjam adni, hogy meddig kell leadnia először, majd azt később még meddig módosíthatja.

De most azt fogom csinálni, hogy lezárom a kérdéseket az adott időpontokban, aztán átírom a Due-t később arra, ameddig módosítani lehet (jellemzően tél), így tudják majd változtatni. Van ennek a megoldásánál sokkal fontosabb feladat is.
