### ISSUE TITLE
Eddig szerzett pontok a táblázatban

### ISSUE THREAD

**Issue by GuberPeter** [bertadenes/tippelde#28]
A szezon a nemzetközi kupa-meccsekkel már elkezdődött, a tippelők pontokat szereztek. Lehetséges lenne, hogy ezeket manuálisan felvigyem a profilokhoz? Elég, ha csak alapból hozzáadok x pontot a tippelőkhöz, nem kell részletezni, hogy hogyan szerezték.

**Comment by bertadenes** [comment]
Letre kell hozni egy tournamentet a korabban szerzett pontoknak (csak hogy kulon legyenek). Ezutan minden felhasznalonak kell egy score object az adott tounamenthez, es ebbe lehet felvinni a pontokat. Alternativa, hogy kiirsz egy kerdest 0 ponttert a regi tournamenthez, es aki arra hajlando valaszolni, annak automatikusan letrejon a score objectje, csak hozza kell adni a pontokat.
A db-bol en be tudunk exportalni/importalni json fileokon keresztul. Ha adok neked egy templatet, akkor megirod ugy, vagy inkabb beviszed az admin feluleten?

**Comment by GuberPeter** [comment]
De ha másik tournamentet hozok létre, hozzá fogja adni a nagy, teljes eredménykövető táblázathoz?

Annyira nem kell sietni, hogy 0 pontos meccseket hozzak létre, meg tudom várni, hogy mindenki tippeljen, aztán majd hozzáadom a pontokat.

**Comment by bertadenes** [comment]
azt hiszem ehhez minden adott, ugyhogy zarom
