### ISSUE TITLE
NB I kieső / NB II feljutó

### ISSUE THREAD

**Issue by GuberPeter** [bertadenes/tippelde#8]
Itt is két rubrika lenne célszerű a 2-2 feljutónak és kiesőnek. Pontozás kialakítása itt is ráér.

Pontozás: 40 pont/találat
Módosítás lehetséges télig, módosítás után járó pontok: 10/találat.

**Comment by bertadenes** [comment]
itt azt javaslom ket-ket kerdest irjunk ki, pl kieso1 kieso2, award 40, penalty 30, changes 1
ha valaki tobbet akar modositani, akkor azt majd megoldjuk

**Comment by GuberPeter** [comment]
Rendben. Ne módosítgassanak többet. Eredetileg ezt eleve csak télen lehetne, akkor így egyszerűbb is.
